/*
 * VMware Bifröst Garden
 * Planting seeds and watching them grow.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dshanley@vmware.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
